DECLARE @MaxID AS INT;
SELECT @MaxID = MAX(RRFLevel1ID)
FROM dbo.C_RRFLevel1
WHERE RRFLevel1ID < 1000
DBCC CHECKIDENT (C_RRFLevel1, RESEED, @MaxID)
--
SELECT @MaxID = MAX(IELevel1ID)
FROM dbo.C_IELevel1
WHERE IELevel1ID < 1000
--SELECT @MaxID
DBCC CHECKIDENT (C_IELevel1, RESEED, @MaxID)
--
SELECT @MaxID = MAX(IRRMFLevel1ID)
FROM dbo.C_IRRMFLevel1
WHERE IRRMFLevel1ID < 1000
--SELECT @MaxID
DBCC CHECKIDENT (C_IRRMFLevel1, RESEED, @MaxID)
--
SELECT @MaxID = MAX(LDFPLevel1ID)
FROM dbo.C_LDFPLevel1
WHERE LDFPLevel1ID < 1000
--SELECT @MaxID
DBCC CHECKIDENT (C_LDFPLevel1, RESEED, @MaxID)
--

DECLARE @MaxID AS INT
SELECT @MaxID = MAX(IndicatorLDFPLevelID)
FROM dbo.IndicatorLDFPLevel
WHERE IndicatorLDFPLevelID < 1000
--SELECT @MaxID
DBCC CHECKIDENT (IndicatorLDFPLevel, RESEED, @MaxID)

SELECT IDENT_CURRENT('C_IRRMLevel1')


SELECT *
FROM dbo.C_IRRMFLevel1
